CREATE TABLE roles (
  id SERIAL UNIQUE,
  name VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

-- Insert `ADMIN` and `READ` roles.
INSERT INTO roles (name) VALUES ('ADMIN');
INSERT INTO roles (name) VALUES ('READ');
