CREATE TABLE stores (
  id SERIAL UNIQUE,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  url_name VARCHAR(50),
  created_by INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES vendors(id)
);